[general]
import = [
    "~/.config/alacritty/themes/duskfox/duskfox.toml"
]

[font]

normal.family = "Commit Mono Nerd Font"
bold.family = "Commit Mono Nerd Font"
italic.family = "Commit Mono Nerd Font"
bold_italic.family = "Commit Mono Nerd Font"
